name: Build Kernel on AArch64

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      kernel_repo:
        description: 'Kernel repository to build'
        required: true
        default: 'Mayuri-Chan/android_kernel_xiaomi_gale'
      kernel_branch:
        description: 'Kernel branch to build'
        required: true
        default: 'stable'
      kernel_defconfig:
        description: 'defconfig to build the kernel'
        required: true
        default: 'gale_defconfig'
      kernel_img:
        description: 'Kernel image name'
        required: false
        default: 'Image.gz'
      kernel_dtb:
        description: 'Kernel dtb name'
        required: false
        default: 'mediatek/mt6768.dtb'


jobs:
  build_normal:
    name: Build Normal
    uses: ./.github/workflows/build.yml
    with:
      build_type: "normal"
      kernel_repo: ${{ github.event.inputs.kernel_repo }}
      kernel_branch: ${{ github.event.inputs.kernel_branch }}
      kernel_defconfig: ${{ github.event.inputs.kernel_defconfig }}
      kernel_img: ${{ github.event.inputs.kernel_img }}
      kernel_dtb: ${{ github.event.inputs.kernel_dtb }}
    secrets: inherit

  build_ksu:
    name: Build KernelSU
    uses: ./.github/workflows/build.yml
    with:
      build_type: "ksu"
      kernel_repo: ${{ github.event.inputs.kernel_repo }}
      kernel_branch: ${{ github.event.inputs.kernel_branch }}
      kernel_defconfig: ${{ github.event.inputs.kernel_defconfig }}
      kernel_img: ${{ github.event.inputs.kernel_img }}
      kernel_dtb: ${{ github.event.inputs.kernel_dtb }}
    secrets: inherit

  build_susfs:
    name: Build KernelSUS
    uses: ./.github/workflows/build.yml
    with:
      build_type: "susfs"
      kernel_repo: ${{ github.event.inputs.kernel_repo }}
      kernel_branch: ${{ github.event.inputs.kernel_branch }}
      kernel_defconfig: ${{ github.event.inputs.kernel_defconfig }}
      kernel_img: ${{ github.event.inputs.kernel_img }}
      kernel_dtb: ${{ github.event.inputs.kernel_dtb }}
    secrets: inherit
